"""All NS-reachable stations (NL + B + D + F + GB), pulled from
https://gateway.apiportal.ns.nl/reisinformatie-api/api/v2/stations.
Snapshot date: 2026-04-29.
"""

_RAW_STATIONS: list[str] = [
    "'s-Hertogenbosch", "'s-Hertogenbosch Oost", "'t Harde", 'Aachen Hbf', 'Aachen Rothe Erde',
    'Aachen Schanz', 'Aachen West', 'Aalten', 'Aarschot', 'Abcoude', 'Ahaus', 'Aime-la-Plagne',
    'Airport Charles de Gaulle', 'Aix-en-Provence TGV', 'Akkrum', 'Albertville', 'Alkmaar',
    'Alkmaar Noord', 'Almelo', 'Almelo de Riet', 'Almere Buiten', 'Almere Centrum',
    'Almere Muziekwijk', 'Almere Oostvaarders', 'Almere Parkwijk', 'Almere Poort',
    'Alphen a/d Rijn', 'Altenberge', 'Amersfoort Centraal', 'Amersfoort Schothorst',
    'Amersfoort Vathorst', 'Amsterdam Amstel', 'Amsterdam Bijlmer ArenA', 'Amsterdam Centraal',
    'Amsterdam Holendrecht', 'Amsterdam Lelylaan', 'Amsterdam Muiderpoort', 'Amsterdam RAI',
    'Amsterdam Science Park', 'Amsterdam Sloterdijk', 'Amsterdam Zuid', 'Angermünde',
    'Anna Paulowna', 'Antwerpen-Berchem', 'Antwerpen-Centraal', 'Antwerpen-Luchtbal',
    'Antwerpen-Noorderdokken', 'Antwerpen-Zuid', 'Apeldoorn', 'Apeldoorn De Maten',
    'Apeldoorn Osseveld', 'Appingedam', 'Arkel', 'Arnemuiden', 'Arnhem Centraal',
    'Arnhem Presikhaaf', 'Arnhem Velperpoort', 'Arnhem Zuid', 'Aschaffenburg',
    'Ashford International', 'Assen', 'Augsburg Hbf', 'Avignon TGV', 'Baarn', 'Bad Bentheim',
    'Bad Nieuweschans', 'Bad Oeynhausen', 'Bad Schandau', 'Baden-Baden', 'Baflo', 'Barendrecht',
    'Barneveld Centrum', 'Barneveld Noord', 'Barneveld Zuid', 'Basel Bad Bf', 'Bedum',
    'Beek-Elsloo', 'Beesd', 'Beilen', 'Belsele', 'Bergen op Zoom', 'Berlin Betr Rummelsburg',
    'Berlin Gesundbrunnen', 'Berlin Hbf', 'Berlin Ostbahnhof', 'Berlin Südkreuz', 'Berlin Zoo',
    'Berlin-Schönefeld Flugh.', 'Berlin-Spandau', 'Bernau (B Berlin)', 'Best', 'Beveren',
    'Beverwijk', 'Bielefeld Hbf', 'Bilthoven', 'Bilzen', 'Blerick', 'Bloemendaal', 'Bocholt',
    'Bochum Hbf', 'Bodegraven', 'Boisheim', 'Bonn Hbf', 'Bonn-Beuel', 'Boom', 'Bork (Westf)',
    'Borne', 'Boskoop', 'Boskoop Snijdelwijk', 'Bourg-St-Maurice', 'Boven-Hardinxveld',
    'Bovenkarspel Flora', 'Bovenkarspel-Grootebroek', 'Boxmeer', 'Boxtel', 'Brake (b Bielefeld)',
    'Braunschweig Hbf', 'Breda', 'Breda-Prinsenbeek', 'Bremen Hbf', 'Bressoux', 'Breukelen',
    'Breyell', 'Bruchmühlen', 'Brummen', 'Brussel-Centraal', 'Brussel-Noord', 'Brussel-Zuid',
    'Brussels Airport-Zaventem', 'Buitenpost', 'Bunde', 'Bunde (D)', 'Bunnik', 'Bussum Zuid',
    'Bönen', 'Bünde (Westf)', 'Capelle Schollevaar', 'Castricum', 'Celle', 'Chambéry',
    'Chevremont', 'Coesfeld (Westf)', 'Coevorden', 'Cuijk', 'Culemborg', 'Daarlerveen', 'Dalen',
    'Dalfsen', 'De Vink', 'De Westereen', 'Deinum', 'Delden', 'Delft', 'Delft Campus', 'Delfzijl',
    'Delfzijl West', 'Den Dolder', 'Den Haag Centraal', 'Den Haag HS', 'Den Haag Laan v NOI',
    'Den Haag Mariahoeve', 'Den Haag Moerwijk', 'Den Haag Ypenburg', 'Den Helder',
    'Den Helder Zuid', 'Deurne', 'Deventer', 'Deventer Colmschate', 'Didam', 'Diemen',
    'Diemen Zuid', 'Diepenbeek', 'Dieren', 'Dinslaken', 'Doetinchem', 'Doetinchem De Huet',
    'Dordrecht', 'Dordrecht Stadspolders', 'Dordrecht Zuid', 'Dortmund Hbf', 'Dortmund-Derne',
    'Dortmund-Kirchderne', 'Dresden Hbf', 'Dresden-Neustadt', 'Driebergen-Zeist', 'Driehuis',
    'Dronryp', 'Dronten', 'Duffel', 'Duisburg Hbf', 'Duiven', 'Duivendrecht', 'Dülken', 'Dülmen',
    'Düren', 'Düsseldorf Flughafen', 'Düsseldorf Hbf', 'Düsseldorf-Bilk',
    'Ebbsfleet International', 'Eberswalde Hbf', 'Echt', 'Ede Centrum', 'Ede-Wageningen',
    'Eemshaven', 'Eijsden', 'Eilendorf', 'Eindhoven Centraal', 'Eindhoven Strijp-S', 'Ekeren',
    'Elst', 'Emmen', 'Emmen Zuid', 'Emmerich', 'Emmerich-Elten', 'Empel-Rees', 'Enkhuizen',
    'Ennepetal', 'Enschede', 'Enschede De Eschmarke', 'Enschede Kennispark', 'Epe (Westf)',
    'Ermelo', 'Eschweiler Hbf', 'Eschweiler Talbahnhof', 'Eschweiler-Nothberg',
    'Eschweiler-Weisweiler', 'Eschweiler-West', 'Essen', 'Essen hbf', 'Esslingen (Neckar)',
    'Etten-Leur', 'Eygelshoven', 'Eygelshoven Markt', 'Feanwâlden', 'Flensburg', 'Franeker',
    'Frankfurt (M) Hbf', 'Frankfurt (Main) Süd', 'Frankfurt (Oder)', 'Frankfurt Flugh. Regiobf.',
    'Frankfurt Flughafen Fernb', 'Freiburg (Breisgau) Hbf', 'Friedrichsfeld (Niederrh)', 'Fulda',
    'Gaanderen', 'Garmisch-Partenkirchen', 'Geislingen', 'Geldermalsen', 'Geldrop', 'Geleen Oost',
    'Geleen-Lutterade', 'Gelsenkirchen Hbf', 'Gilze-Rijen', 'Glanerbrug', 'Glons', 'Goes', 'Goor',
    'Gorinchem', 'Gouda', 'Gouda Goverwelle', 'Gramsbergen', 'Grijpskerk', 'Gronau (Westf.)',
    'Groningen', 'Groningen Europapark', 'Groningen Noord', 'Grou-Jirnsum', 'Göppingen',
    'Günzburg', 'H-Altona Max Brauer Allee', 'Haarlem', 'Haarlem Spaarnwoude', 'Hagen Hbf',
    'Haldern (Rheinl)', 'Halfweg-Zwanenburg', 'Hamburg Dammtor', 'Hamburg Hbf', 'Hamburg-Altona',
    'Hamburg-Altona(S)', 'Hamburg-Bergedorf', 'Hamburg-Harburg', 'Hamm (Westf.)', 'Hannover Hbf',
    'Hannover Hbf ZOB', 'Hannover Messe/Laatzen', 'Hardenberg', 'Harderwijk',
    'Hardinxveld Blauwe Zoom', 'Hardinxveld-Giessendam', 'Haren', 'Harlingen', 'Harlingen Haven',
    'Harwich International', 'Heemskerk', 'Heemstede-Aerdenhout', 'Heerenveen',
    'Heerenveen IJsstadion', 'Heerhugowaard', 'Heerlen', 'Heerlen Woonboulevard', 'Heeze',
    'Heide (B)', 'Heiloo', 'Heimbach(Nahe)', 'Heino', 'Helmond', "Helmond 't Hout",
    'Helmond Brandevoort', 'Helmond Brouwhuis', 'Helmstedt', 'Hemiksem', 'Hemmen-Dodewaard',
    'Hengelo', 'Hengelo Gezondheidspark', 'Hengelo Oost', 'Herford', 'Herstal', 'Herzogenrath',
    'Hiddenhausen-Schweicheln', 'Hillegom', 'Hilversum', 'Hilversum Media Park',
    'Hilversum Sportpark', 'Hindeloopen', 'Hoboken-Polder', 'Hoensbroek', 'Hoevelaken',
    'Hollandsche Rading', 'Holten', 'Holzwickede', 'Hoofddorp', 'Hoogeveen', 'Hoogezand-Sappemeer',
    'Hoogkarspel', 'Hoorn', 'Hoorn Kersenboogerd', 'Horst-Sevenum', 'Houten', 'Houten Castellum',
    'Houthem-St. Gerlach', 'Hove', 'Hurdegaryp', 'Hörstel', 'IJlst', 'Ibbenbüren',
    'Ibbenbüren-Esch', 'Ibbenbüren-Laggenbeck', 'Ingolstadt Hbf', 'Kaldenkirchen', 'Kalmthout',
    'Kampen', 'Kampen Zuid', 'Kapelle-Biezelinge', 'Kapellen', 'Karlsruhe Hbf',
    'Kassel-Wilhelmshöhe', 'Kerkrade Centrum', 'Kesteren', 'Kiel Hbf', 'Kijkuit', 'Kirchlengern',
    'Klarenbeek', 'Klimmen-Ransdaal', 'Koblenz Hbf', 'Kohlscheid', 'Kontich', 'Koog aan de Zaan',
    'Koudum-Molkwerum', 'Krabbendijke', 'Krommenie-Assendelft', 'Kropswolde', 'Kruiningen-Yerseke',
    'Köln Hbf', 'Köln Messe/Deutz', 'Köln Süd', 'Köln West', 'Köln-Ehrenfeld', 'Köln-Mülheim',
    'Lage Zwaluwe', 'Landgraaf', 'Landry', 'Langerwehe', 'Lansingerland-Zoetermeer',
    'Leer (Ostfriesl)', 'Leerdam', 'Leeuwarden', 'Leeuwarden Camminghaburen', 'Legden', 'Lehrte',
    'Leiden Centraal', 'Leiden Lammenschans', 'Leipzig Hbf', 'Lelystad Centrum',
    'Lette (Kr Coesfeld)', 'Lichtenvoorde-Groenlo', 'Liers', 'Lille Europe', 'Lille Flandres',
    'Limburg Süd', 'Liège-Guillemins', 'Lochem', 'Lokeren', 'London St. Pancras Int.', 'Loppersum',
    'Lourdes', 'Ludwigslust', 'Lunteren', 'Lübeck Hbf', 'Lüdinghausen', 'Lüneburg', 'Lünen Hbf',
    'Maarheeze', 'Maarn', 'Maarssen', 'Maastricht', 'Maastricht Noord', 'Maastricht Randwyck',
    'Magdeburg Hbf', 'Mainz Hbf', 'Mannheim Hbf', 'Mantgum', 'Mariënberg',
    'Marne-la-Vallée-Chessy', 'Marseille-St-Charles', 'Martenshoek', 'Mechelen',
    'Mechelen-Nekkerspoel', 'Meerssen', 'Mehrhoog', 'Melle', 'Melsele', 'Meppel', 'Merelbeke',
    'Metelen Land', 'Middelburg', 'Millingen(b Rees)', 'Milmort', 'Minden (Westf)', 'Montabaur',
    'Mook-Molenhoek', 'Mortsel-Deurnesteenweg', 'Mortsel-Oude God', 'Moutiers-Salins-Brides',
    'Murnau', 'Mönchengladbach Hbf', 'München Hbf', 'München Ost', 'München-Pasing',
    'Münster (W) Zentrum Nord', 'Münster (Westf) Hbf', 'Münster-Häger', 'Naarden-Bussum',
    'Neumünster', 'Neuss Hbf', 'Niel', 'Nieuw Amsterdam', 'Nieuw Vennep', 'Nieuwerkerk a/d IJssel',
    'Nieuwkerken-Waas', 'Nijkerk', 'Nijmegen', 'Nijmegen Dukenburg', 'Nijmegen Goffert',
    'Nijmegen Heyendaal', 'Nijmegen Lent', 'Nijverdal', 'Noorderkempen', 'Nordwalde', 'Nunspeet',
    'Nuth', 'Nürnberg Hbf', 'Obdam', 'Oberau', 'Oberhausen Hbf', 'Oberhausen-Holten',
    'Oberhausen-Sterkrade', 'Ochtrup', 'Offenburg', 'Oisterwijk', 'Oldenburg Hbf', 'Oldenzaal',
    'Olst', 'Ommen', 'Oosterbeek', 'Opheusden', 'Osnabrück Altstadt', 'Osnabrück Hbf', 'Oss',
    'Oss West', 'Oudenbosch', 'Overveen', 'Paris-Nord', 'Passau Hbf', 'Plochingen', 'Praest',
    'Preussen', 'Pulheim', 'Purmerend', 'Purmerend Overwhere', 'Purmerend Weidevenne', 'Putten',
    'Puurs', 'Raalte', 'Rathenow', 'Ravenstein', 'Regensburg Hbf', 'Reuver', 'Rheden', 'Rheine',
    'Rhenen', 'Rijssen', 'Rijswijk', 'Rilland-Bath', 'Ringsheim/Europa-Park', 'Roermond',
    'Rommerskirchen', 'Roodeschool', 'Roosendaal', 'Rosendahl-Holtwick', 'Rosenheim', 'Rosmalen',
    'Rotterdam Alexander', 'Rotterdam Blaak', 'Rotterdam Centraal', 'Rotterdam Lombardijen',
    'Rotterdam Noord', 'Rotterdam Stadion', 'Rotterdam Zuid', 'Ruisbroek-Sauvegarde', 'Ruurlo',
    'Salzbergen', 'Salzwedel', 'Santpoort Noord', 'Santpoort Zuid', 'Sassenheim', 'Sauwerd',
    'Schaerbeek', 'Schagen', 'Scheemda', 'Schelle', 'Schiedam Centrum', 'Schin op Geul',
    'Schinnen', 'Schiphol Airport', 'Schleswig', 'Schwelm', 'Schwerte (Ruhr)', 'Schüttorf', 'Selm',
    'Selm-Beifang', 'Siegburg/Bonn', 'Siegen Hbf', 'Sinaai', 'Singen(Hohentwiel)',
    'Sint-Katelijne-Waver', 'Sint-Mariaburg', 'Sint-Niklaas', 'Sittard', 'Sliedrecht',
    'Sliedrecht Baanhoek', 'Sneek', 'Sneek Noord', 'Soest', 'Soest Zuid', 'Soestdijk', 'Spaubeek',
    'Stavoren', 'Stedum', 'Steenwijk', 'Steinfurt-Borghorst', 'Steinfurt-Burgsteinfurt',
    'Steinfurt-Grottenkamp', 'Stendal', 'Stolberg Mühlener Bahnhof', 'Stolberg Rathaus',
    'Stolberg(Rhein)Hbf', 'Stolberg-Schneidmühle', 'Stommeln', 'Straubing', 'Stuttgart Hbf',
    'Susteren', 'Swalmen', 'Tegelen', 'Terborg', 'Tiel', 'Tiel Passewaaij', 'Tilburg',
    'Tilburg Reeshof', 'Tilburg Universiteit', 'Tongeren', 'Troisdorf', 'Twello', 'Uelzen',
    'Uitgeest', 'Uithuizen', 'Uithuizermeeden', 'Ulm Hbf', 'Unna', 'Usquert', 'Utrecht Centraal',
    'Utrecht Leidsche Rijn', 'Utrecht Lunetten', 'Utrecht Maliebaan', 'Utrecht Overvecht',
    'Utrecht Terwijde', 'Utrecht Vaartsche Rijn', 'Utrecht Zuilen', 'Vaihingen(Enz)',
    'Valence TGV', 'Valkenburg', 'Varsseveld', 'Veendam', 'Veenendaal Centrum', 'Veenendaal West',
    'Veenendaal-De Klomp', 'Velp', 'Venlo', 'Venray', 'Vierlingsbeek', 'Viersen', 'Vilvoorde',
    'Visé', 'Vleuten', 'Vlissingen', 'Vlissingen Souburg', 'Voerde (Niederrhein)', 'Voerendaal',
    'Voorburg', 'Voorhout', 'Voorschoten', 'Voorst-Empe', 'Vorden', 'Vriezenveen', 'Vroomshoop',
    'Vught', 'Waddinxveen', 'Waddinxveen Noord', 'Waddinxveen Triangel', 'Warffum', 'Weener',
    'Weert', 'Weesp', 'Wehl', 'Weilheim (Oberbay)', 'Wesel', 'Wesel Feldmark', 'Westerhausen',
    'Westervoort', 'Wezep', 'Wierden', 'Wiesbaden Hbf', 'Wijchen', 'Wijhe', 'Wildert',
    'Winschoten', 'Winsum', 'Winterswijk', 'Winterswijk West', 'Wissingen', 'Wittenberge',
    'Woerden', 'Wolfheze', 'Wolfsburg Hbf', 'Wolvega', 'Workum', 'Wormerveer', 'Wunstorf',
    'Wuppertal Hbf', 'Wuppertal-Barmen', 'Wuppertal-Oberbarmen', 'Wuppertal-Vohwinkel',
    'Würzburg Hbf', 'Zaandam', 'Zaandam Kogerveld', 'Zaandijk Zaanse Schans', 'Zaltbommel',
    'Zandvoort aan Zee', 'Zetten-Andelst', 'Zevenaar', 'Zevenbergen', 'Zoetermeer',
    'Zoetermeer Oost', 'Zuidbroek', 'Zuidhorn', 'Zutphen', 'Zwijndrecht', 'Zwijndrecht (B)',
    'Zwolle', 'Zwolle Stadshagen',
]

STATIONS: list[str] = sorted(set(_RAW_STATIONS))
