"""Hard-coded list of Dutch railway stations.

Long-term this would be better generated from the NS stations API,
but a static list keeps the config flow free of network calls.
Deduplicated and alphabetised on import.
"""

_RAW_STATIONS: list[str] = [
    "'t Harde", "Aalten", "Abcoude", "Akkrum", "Alkmaar", "Alkmaar Noord", "Almelo", "Almelo de Riet",
    "Almere Buiten", "Almere Centrum", "Almere Muziekwijk", "Almere Oostvaarders", "Almere Parkwijk", "Almere Poort",
    "Alphen a/d Rijn", "Amersfoort Centraal", "Amersfoort Schothorst", "Amersfoort Vathorst", "Amstelveen",
    "Amsterdam Amstel", "Amsterdam Arena", "Amsterdam Bijlmer Arena", "Amsterdam Centraal", "Amsterdam Holendrecht",
    "Amsterdam Lelylaan", "Amsterdam Muiderpoort", "Amsterdam RAI", "Amsterdam Science Park", "Amsterdam Sloterdijk",
    "Amsterdam Zuid", "Anna Paulowna", "Apeldoorn", "Apeldoorn De Maten", "Apeldoorn Osseveld", "Appingedam",
    "Arnemuiden", "Arnhem Centraal", "Arnhem Presikhaaf", "Arnhem Velperpoort", "Arnhem Zuid", "Assen",
    "Baarn", "Baflo", "Barendrecht", "Barneveld Centrum", "Barneveld Noord", "Barneveld Zuid", "Bedum",
    "Beek-Elsloo", "Beesd", "Beilen", "Bergen op Zoom", "Best", "Beverwijk", "Bilthoven", "Blerick",
    "Bloemendaal", "Bodegraven", "Borne", "Boskoop", "Boskoop Snijdelwijk", "Bovenkarspel Flora",
    "Bovenkarspel-Grootebroek", "Boxmeer", "Boxtel", "Breda", "Breda-Prinsenbeek", "Breukelen", "Brouwhuis",
    "Buitenpost", "Bunde", "Bunnik", "Bussum Zuid", "Capelle Schollevaar", "Castricum",
    "Chevremont", "Coevorden", "Cuijk", "Culemborg", "Daarlerveen", "Dalen", "Dalfsen", "De Vink",
    "De Westereen", "Deinum", "Delden", "Delft", "Delft Campus", "Delfzijl", "Delfzijl West", "Den Dolder",
    "Den Haag Centraal", "Den Haag HS", "Den Haag Laan v NOI", "Den Haag Mariahoeve", "Den Haag Moerwijk",
    "Den Haag Ypenburg", "Den Helder", "Den Helder Zuid", "Deurne", "Deventer", "Deventer Colmschate",
    "Didam", "Diemen", "Diemen Zuid", "Dieren", "Doetinchem", "Doetinchem De Huet", "Dordrecht",
    "Dordrecht Stadspolders", "Dordrecht Zuid", "Driebergen-Zeist", "Driehuis", "Dronten", "Dronryp",
    "Duiven", "Duivendrecht", "Echt", "Ede Centrum", "Ede-Wageningen", "Eemshaven", "Eijsden",
    "Eindhoven Centraal", "Eindhoven Strijp-S", "Elst", "Emmen", "Emmen Zuid", "Enkhuizen", "Enschede",
    "Enschede Kennispark", "Enschede De Eschmarke", "Ermelo", "Etten-Leur", "Eygelshoven", "Eygelshoven Markt",
    "Feanwalden", "Gaanderen", "Geldermalsen", "Geldrop", "Geleen Oost", "Geleen-Lutterade", "Gilze-Rijen",
    "Glanerbrug", "Goes", "Goor", "Gorinchem", "Gouda", "Gouda Goverwelle", "Gramsbergen", "Grijpskerk",
    "Groningen", "Groningen Europapark", "Groningen Noord", "Grou-Jirnsum", "Haarlem", "Haarlem Spaarnwoude",
    "Halfweg-Zwanenburg", "Hardenberg", "Harderwijk", "Hardinxveld Blauwe Zoom", "Hardinxveld-Giessendam",
    "Haren", "Harlingen", "Harlingen Haven", "Heemskerk", "Heemstede-Aerdenhout", "Heerenveen",
    "Heerenveen IJsstadion", "Heerhugowaard", "Heerlen", "Heerlen Woonboulevard", "Heeze", "Heiloo",
    "Heino", "Helmond", "Helmond Brandevoort", "Helmond 't Hout", "Helmond Brouwhuis", "Hemmen-Dodewaard",
    "Hengelo", "Hengelo Gezondheidspark", "Hengelo Oost", "Hillegom", "Hilversum", "Hilversum Media Park",
    "Hilversum Sportpark", "Hindeloopen", "Hoensbroek", "Hoevelaken", "Holten", "Hoofddorp", "Hoogeveen",
    "Hoogezand-Sappemeer", "Hoogkarspel", "Hoorn", "Hoorn Kersenboogerd", "Horst-Sevenum", "Houten",
    "Houten Castellum", "Houthem-St. Gerlach", "Hurdegaryp", "IJlst", "IJmuiden", "Kampen", "Kampen Zuid",
    "Kapelle-Biezelinge", "Kerkrade Centrum", "Kesteren", "Klarenbeek", "Klimmen-Ransdaal", "Koog aan de Zaan",
    "Koudum-Molkwerum", "Krabbendijke", "Krommenie-Assendelft", "Kropswolde", "Kruiningen-Yerseke",
    "Lansingerland-Zoetermeer", "Landgraaf", "Leerdam", "Leeuwarden", "Leeuwarden Camminghaburen", "Leiden Centraal",
    "Leiden Lammenschans", "Lelystad Centrum", "Lichtenvoorde-Groenlo", "Lochem", "Loppersum", "Lunteren",
    "Maarheeze", "Maarn", "Maarssen", "Maastricht", "Maastricht Noord", "Maastricht Randwyck", "Mantgum",
    "Marienberg", "Martenshoek", "Meerssen", "Meppel", "Middelburg", "Mook-Molenhoek", "Naarden-Bussum",
    "Nieuw Amsterdam", "Nieuw Vennep", "Nieuwerkerk a/d IJssel", "Nijkerk", "Nijmegen", "Nijmegen Dukenburg",
    "Nijmegen Goffert", "Nijmegen Heyendaal", "Nijmegen Lent", "Nijverdal", "Nunspeet", "Nuth", "Obdam",
    "Oisterwijk", "Oldenzaal", "Olst", "Ommen", "Oosterbeek", "Opheusden", "Oss", "Oss West", "Oudenbosch",
    "Overveen", "Purmerend", "Purmerend Overwhere", "Purmerend Weidevenne", "Putten", "Raalte", "Ravenstein",
    "Reuver", "Rheden", "Rhenen", "Rijssen", "Rilland-Bath", "Roermond", "Roodeschool", "Roosendaal",
    "Rosmalen", "Rotterdam Alexander", "Rotterdam Blaak", "Rotterdam Centraal", "Rotterdam Lombardijen",
    "Rotterdam Noord", "Rotterdam Stadion", "Rotterdam Zuid", "Ruurlo", "Santpoort Noord", "Santpoort Zuid",
    "Sappemeer Oost", "Sassenheim", "Sauwerd", "Schagen", "Scheemda", "Schiedam Centrum", "Schin op Geul",
    "Schinnen", "Schiphol Airport", "Sittard", "Sliedrecht", "Sliedrecht Baanhoek", "Sneek", "Sneek Noord",
    "Soest", "Soest Zuid", "Soestdijk", "Spaubeek", "Stavoren", "Stedum", "Steenwijk", "Stein", "Susteren",
    "Swalmen", "Tegelen", "Terborg", "Tiel", "Tiel Passewaaij", "Tilburg", "Tilburg Reeshof",
    "Tilburg Universiteit", "Twello", "Uitgeest", "Uithuizen", "Uithuizermeeden", "Utrecht Centraal",
    "Utrecht Leidsche Rijn", "Utrecht Lunetten", "Utrecht Maliebaan", "Utrecht Overvecht", "Utrecht Terwijde",
    "Utrecht Vaartsche Rijn", "Utrecht Zuilen", "Valkenburg", "Varsseveld", "Veendam", "Veenendaal Centrum",
    "Veenendaal West", "Veenendaal-De Klomp", "Velp", "Venlo", "Venray", "Vierlingsbeek", "Vleuten",
    "Vlissingen", "Vlissingen Souburg", "Voerendaal", "Voorburg", "Voorhout", "Voorschoten", "Voorst-Empe",
    "Vorden", "Vriezenveen", "Vroomshoop", "Vught", "Waddinxveen", "Waddinxveen Noord", "Waddinxveen Triangel",
    "Warffum", "Weert", "Weesp", "Wehl", "Westervoort", "Wezep", "Wierden", "Wijchen", "Wijhe", "Winschoten",
    "Winsum", "Winterswijk", "Winterswijk West", "Woerden", "Wolfheze", "Wolvega", "Workum", "Wormerveer",
    "Zaandam", "Zaandam Kogerveld", "Zaandijk Zaanse Schans", "Zaltbommel", "Zandvoort aan Zee", "Zetten-Andelst",
    "Zevenaar", "Zevenbergen", "Zoetermeer", "Zoetermeer Oost", "Zuidbroek", "Zuidhorn", "Zutphen", "Zwolle",
    "Zwolle Stadshagen", "Zwijndrecht",
]

STATIONS: list[str] = sorted(set(_RAW_STATIONS))
